# Generated by Django 5.1.7 on 2026-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WholeSeller', '0002_alter_bulkmedicine_medicine_file_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkmedicine',
            name='medicine_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
