# Generated by Django 5.1.7 on 2026-01-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WholeSeller', '0003_alter_bulkmedicine_medicine_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkmedicine',
            name='medicine_file',
        ),
        migrations.AddField(
            model_name='bulkmedicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/'),
        ),
    ]
