# Generated by Django 5.1.7 on 2026-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WholeSeller', '0006_remove_medicine_medicine_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
