# Generated by Django 5.1.7 on 2026-01-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_labtestitems_labtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='doctor/')),
                ('img2', models.ImageField(upload_to='doctor/')),
                ('img3', models.ImageField(upload_to='doctor/')),
            ],
        ),
    ]
