# Generated by Django 5.1.7 on 2026-01-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='doctor_profile/')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
            ],
        ),
    ]
