# Generated by Django 5.1.7 on 2026-01-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
