# Generated by Django 5.1.7 on 2026-01-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expdate', models.DateField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='user.medicine')),
            ],
        ),
    ]
