# Generated by Django 5.1.7 on 2026-01-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
    ]
