# Generated by Django 5.1.7 on 2026-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_selleruser_wholeselleruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selleruser',
            old_name='phone',
            new_name='owner_phone',
        ),
        migrations.RenameField(
            model_name='selleruser',
            old_name='address',
            new_name='store_address',
        ),
        migrations.RenameField(
            model_name='selleruser',
            old_name='city',
            new_name='store_city',
        ),
        migrations.RenameField(
            model_name='selleruser',
            old_name='state',
            new_name='store_license',
        ),
        migrations.RenameField(
            model_name='selleruser',
            old_name='pincode',
            new_name='store_pincode',
        ),
        migrations.RenameField(
            model_name='wholeselleruser',
            old_name='address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='wholeselleruser',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.AddField(
            model_name='selleruser',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_logos/'),
        ),
        migrations.AddField(
            model_name='selleruser',
            name='store_state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selleruser',
            name='store_timing',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wholeselleruser',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='wholeseller_logos/'),
        ),
        migrations.AddField(
            model_name='wholeselleruser',
            name='license_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selleruser',
            name='gst_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wholeselleruser',
            name='gst_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
