# Generated by Django 5.1.7 on 2026-01-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_phone_selleruser_owner_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholeselleruser',
            old_name='email',
            new_name='owner_email',
        ),
        migrations.RenameField(
            model_name='wholeselleruser',
            old_name='contact_phone',
            new_name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='wholeselleruser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='wholeselleruser',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='wholeselleruser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wholeselleruser',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='wholeselleruser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='wholeselleruser',
            name='state',
        ),
        migrations.AddField(
            model_name='wholeselleruser',
            name='owner_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wholeselleruser',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wholeselleruser',
            name='gst_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wholeselleruser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
