# Generated by Django 5.1.7 on 2026-01-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_email_wholeselleruser_owner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='price',
            field=models.IntegerField(),
        ),
    ]
