# Generated by Django 5.1.7 on 2026-01-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_medicinedetails_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img1', models.ImageField(upload_to='crosusel/')),
                ('img2', models.ImageField(upload_to='crosusel/')),
                ('img3', models.ImageField(upload_to='crosusel/')),
            ],
        ),
    ]
