# Generated by Django 5.1.7 on 2026-01-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_crosusel'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosusel',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crosusel',
            name='description3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crosusel',
            name='title2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crosusel',
            name='title3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
